# Generated by Django 5.2.9 on 2026-01-03 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='postModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=10)),
                ('post_image', models.ImageField(upload_to='posts/')),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
