# Generated by Django 5.2.9 on 2026-01-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='post_title',
            field=models.CharField(max_length=50),
        ),
    ]
